variables:
#  CODECOV_TOKEN: "ccd0e0ce-a5bd-4219-b6cc-c789dca79be1"
  _R_CHECK_CRAN_INCOMING_: "false"
  _R_CHECK_FORCE_SUGGESTS_: "true"
  APT_PKGS: "libcurl4-openssl-dev libssh2-1-dev libssl-dev libxml2-dev zlib1g-dev git libgsl0-dev"

image: rocker/tidyverse

before_script:
  - apt-get update
#    - apt-get install -y --no-install-recommends ${APT_PKGS}
  - apt-get install -y --no-install-recommends qpdf pandoc pandoc-citeproc
  - R -e 'install.packages(c("dplyr", "kableExtra", "knitr", "here"))'
  - R -e 'install.packages(c("ufs", "DiagrammeR", "DiagrammeRsvg", "svglite"))'
  - R -e 'install.packages(c("openxlsx"))'
  - R -e 'remotes::install_gitlab("r-packages/yum")'
  - R -e 'remotes::install_gitlab("r-packages/justifier")'
  - R -e 'install.packages("pkgdown");'

devtools_check:
  stage: test
  script:
    - R -e 'install.packages(c("DiagrammeRsvg","ufs"));devtools::check()'

pages:
  stage: build
  script:
    - R -e 'install.packages("DiagrammeRsvg")'
    - R -e 'install.packages("ufs")'
    - R -e 'pkgdown::build_site();'
#    - mkdir public/img
#    - cp img/hex-logo.png public/img/hex-logo.png
  artifacts:
    paths:
      - public
#  only:
#    - prod

#coverage:
#  stage: deploy
#  tags:
#    - docker
#  image: rocker/tidyverse
#  when: on_success
#  only:
#    - master
#  before_script:
#    - apt-get update
#    - apt-get install -y --no-install-recommends ${APT_PKGS}
#    - apt-get install -y --no-install-recommends qpdf pandoc pandoc-citeproc
#  script:
#    - R -e 'install.packages(c("ggplot2", "gridExtra", "MASS", "minpack.lm"))'
#    - R -e 'install.packages(c("rosetta", "SCRT", "ufs", "viridis"))'
#    - R -e 'devtools::install_gitlab("r-packages/rosetta")'
#    - R -e 'devtools::install_gitlab("r-packages/ufs")'
#    - R -e 'devtools::install()'
#    - R -e 'covr::codecov(type = c("tests", "examples"), quiet = FALSE)'
